xenial:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-circle
  environment:
    - BUILDNODE=xenialbuild
    - TESTNODE=xenialtest
  links:
    - xenialbuild
    - xenialtest

bionic:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=bionicbuild
    - TESTNODE=bionictest
    - ST2_PACKAGES=st2
  links:
    - bionicbuild
    - bionictest
    - rabbitmq
    - mongodb
    - redis

focal:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=focalbuild
    - TESTNODE=focaltest
    - ST2_PACKAGES=st2
  links:
    - focalbuild
    - focaltest
    - rabbitmq
    - mongodb
    - redis

el8:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=centos8build
    - TESTNODE=centos8test
    - ST2_PACKAGES=st2
  links:
    - centos8build
    - centos8test
    - rabbitmq
    - mongodb
    - redis

el7:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-circle
  environment:
    - BUILDNODE=centos7build
    - TESTNODE=centos7test
  links:
    - centos7build
    - centos7test

## Package build nodes
#
xenialbuild:
  image: stackstorm/packagingbuild:xenial
  extends:
    file: docker-compose.override.yml
    service: volumes-circle

bionicbuild:
  image: stackstorm/packagingbuild:bionic
  volumes_from:
    - st2-packages-vol

focalbuild:
  image: stackstorm/packagingbuild:focal
  volumes_from:
    - st2-packages-vol

centos7build:
  image: stackstorm/packagingbuild:centos7
  extends:
    file: docker-compose.override.yml
    service: volumes-circle

centos8build:
  image: stackstorm/packagingbuild:centos8
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

## Package testing nodes
#
xenialtest:
  image: stackstorm/packagingtest:xenial-systemd
  privileged: true
  extends:
    file: docker-compose.override.yml
    service: volumes-circle
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

bionictest:
  image: stackstorm/packagingtest:bionic-systemd
  privileged: true
  volumes_from:
    - st2-packages-vol
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

focaltest:
  image: stackstorm/packagingtest:focal-systemd
  privileged: true
  volumes_from:
    - st2-packages-vol
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

centos7test:
  image: stackstorm/packagingtest:centos7-systemd
  extends:
    file: docker-compose.override.yml
    service: volumes-circle
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup

centos8test:
  image: stackstorm/packagingtest:centos8-systemd
  privileged: true
  cap_add:
    - SYS_ADMIN
  security_opt:
    - seccomp:unconfined
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
