xenial:
  image: quay.io/stackstorm/packagingrunner
  working_dir: /root/st2-packages
  volumes_from:
    - st2-packages-vol
  environment:
    - BUILDNODE=xenialbuild
    - TESTNODE=xenialtest
  links:
    - xenialbuild
    - xenialtest
    - rabbitmq
    - mongodb
    - redis

bionic:
  image: quay.io/stackstorm/packagingrunner
  working_dir: /root/st2-packages
  volumes_from:
    - st2-packages-vol
  environment:
    - BUILDNODE=bionicbuild
    - TESTNODE=bionictest
    - ST2_PACKAGES=st2
  links:
    - bionicbuild
    - bionictest
    - rabbitmq
    - mongodb
    - redis

el8:
  image: quay.io/stackstorm/packagingrunner
  working_dir: /root/st2-packages
  volumes_from:
    - st2-packages-vol
  environment:
    - BUILDNODE=centos8build
    - TESTNODE=centos8test
  links:
    - centos8build
    - centos8test
    - rabbitmq
    - mongodb
    - redis

el7:
  image: quay.io/stackstorm/packagingrunner
  working_dir: /root/st2-packages
  volumes_from:
    - st2-packages-vol
  environment:
    - BUILDNODE=centos7build
    - TESTNODE=centos7test
  links:
    - centos7build
    - centos7test
    - rabbitmq
    - mongodb
    - redis

## Package build nodes
#
xenialbuild:
  image: stackstorm/packagingbuild:xenial
  volumes_from:
    - st2-packages-vol

bionicbuild:
  image: stackstorm/packagingbuild:bionic
  volumes_from:
    - st2-packages-vol

centos7build:
  image: stackstorm/packagingbuild:centos7
  volumes_from:
    - st2-packages-vol

centos8build:
  image: stackstorm/packagingbuild:centos8
  volumes_from:
    - st2-packages-vol

## Package testing nodes
#
xenialtest:
  image: stackstorm/packagingtest:xenial-systemd
  privileged: true
  volumes_from:
    - st2-packages-vol
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

bionictest:
  image: stackstorm/packagingtest:bionic-systemd
  privileged: true
  volumes_from:
    - st2-packages-vol
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

centos7test:
  image: stackstorm/packagingtest:centos7-systemd
  privileged: true
  volumes_from:
    - st2-packages-vol
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup

centos8test:
  image: stackstorm/packagingtest:centos8-systemd
  privileged: true
  cap_add:
    - SYS_ADMIN
  security_opt:
    - seccomp:unconfined
  volumes_from:
    - st2-packages-vol
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
