xenial:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=xenialbuild
    - TESTNODE=xenialtest
  links:
    - xenialbuild
    - xenialtest
    - rabbitmq
    - mongodb

bionic:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=bionicbuild
    - TESTNODE=bionictest
    - ST2_PACKAGES=st2
  links:
    - bionicbuild
    - bionictest
    - rabbitmq
    - mongodb

el8:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=centos8build
    - TESTNODE=centos8test
    - ST2_PACKAGES=st2
  links:
    - centos8build
    - centos8test
    - rabbitmq
    - mongodb


el7:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=centos7build
    - TESTNODE=centos7test
  links:
    - centos7build
    - centos7test
    - rabbitmq
    - mongodb

## Package build nodes
#
xenialbuild:
  image: stackstorm/packagingbuild:xenial
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

bionicbuild:
  image: stackstorm/packagingbuild:bionic
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

centos7build:
  image: stackstorm/packagingbuild:centos7
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

centos8build:
  image: stackstorm/packagingbuild:centos8
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

## Package testing nodes
#
xenialtest:
  image: stackstorm/packagingtest:xenial-systemd
  privileged: true
  extends:
    file: docker-compose.override.yml
    service: volumes-compose
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

bionictest:
  image: stackstorm/packagingtest:bionic-systemd
  privileged: true
  extends:
    file: docker-compose.override.yml
    service: volumes-compose
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

centos7test:
  image: stackstorm/packagingtest:centos7-systemd
  privileged: true
  extends:
    file: docker-compose.override.yml
    service: volumes-compose
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup

centos8test:
  image: stackstorm/packagingtest:centos8-systemd
  privileged: true
  cap_add:
    - SYS_ADMIN
  security_opt:
    - seccomp:unconfined
  extends:
    file: docker-compose.override.yml
    service: volumes-compose
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup

